
import { DataPoint } from './types';

export const nobelPrizeData: DataPoint[] = [
  { id: 1, year: 1901, name: "Wilhelm Röntgen", category: "X-rays", value: 85 },
  { id: 2, year: 1902, name: "Hendrik Lorentz", category: "Magnetism", value: 70 },
  { id: 3, year: 1903, name: "Henri Becquerel", category: "Radioactivity", value: 90 },
  { id: 4, year: 1904, name: "Lord Rayleigh", category: "Gas density", value: 65 },
  { id: 5, year: 1905, name: "Philipp Lenard", category: "Cathode rays", value: 75 },
  { id: 6, year: 1906, name: "J.J. Thomson", category: "Electron", value: 95 },
  { id: 7, year: 1907, name: "Albert Michelson", category: "Light speed", value: 80 },
  { id: 8, year: 1908, name: "Gabriel Lippmann", category: "Photography", value: 60 },
  { id: 9, year: 1909, name: "Guglielmo Marconi", category: "Wireless", value: 88 },
  { id: 10, year: 1910, name: "Johannes van der Waals", category: "Gas laws", value: 72 },
  { id: 11, year: 1911, name: "Wilhelm Wien", category: "Heat radiation", value: 78 },
  { id: 12, year: 1912, name: "Nils Dalén", category: "Gas regulators", value: 55 },
  { id: 13, year: 1913, name: "Heike Kamerlingh Onnes", category: "Low temperature", value: 82 },
  { id: 14, year: 1914, name: "Max von Laue", category: "X-ray diffraction", value: 86 },
  { id: 15, year: 1915, name: "William Bragg", category: "Crystal structure", value: 84 },
  { id: 16, year: 1917, name: "Charles Barkla", category: "X-ray scattering", value: 76 },
  { id: 17, year: 1918, name: "Max Planck", category: "Quantum theory", value: 100 },
  { id: 18, year: 1919, name: "Johannes Stark", category: "Spectroscopy", value: 74 },
  { id: 19, year: 1920, name: "Charles Guillaume", category: "Nickel alloys", value: 58 },
  { id: 20, year: 1921, name: "Albert Einstein", category: "Photoelectric effect", value: 100 },
  { id: 21, year: 1922, name: "Niels Bohr", category: "Atomic structure", value: 98 },
  { id: 22, year: 1923, name: "Robert Millikan", category: "Electron charge", value: 87 },
  { id: 23, year: 1924, name: "Manne Siegbahn", category: "X-ray spectroscopy", value: 81 },
  { id: 24, year: 1925, name: "James Franck", category: "Electron impact", value: 83 },
  { id: 25, year: 1926, name: "Jean Perrin", category: "Atomic reality", value: 79 },
  { id: 26, year: 1927, name: "Arthur Compton", category: "Compton effect", value: 91 },
  { id: 27, year: 1928, name: "Owen Richardson", category: "Thermionic effect", value: 71 },
  { id: 28, year: 1929, name: "Louis de Broglie", category: "Wave nature", value: 89 },
  { id: 29, year: 1930, name: "Chandrasekhara Raman", category: "Light scattering", value: 85 },
  { id: 30, year: 2021, name: "Syukuro Manabe", category: "Climate modeling", value: 95, connections: [31, 32] },
  { id: 31, year: 2021, name: "Klaus Hasselmann", category: "Climate modeling", value: 95, connections: [30, 32] },
  { id: 32, year: 2021, name: "Giorgio Parisi", category: "Complex systems", value: 92, connections: [30, 31] },
];
